### ISSUE TITLE
[Feature Request] Support events while playing animation

### ISSUE THREAD

**Issue by m1pro** [mwganson/animator#3]
At the moment while playing the animation the user inputs are blocked. Can't rotate the 3d view while playing and can't interrupt the animation.
Would be great if this can be supported/fixed.

**Comment by mwganson** [comment]
You should be able to do these things.  Double click on the tree view icon to stop the animation.  You should be able to rotate the view (although the responsiveness might not be very good).  Each step through the loop a call is made to FreeCADGui.updateGui() for this purpose.  See line #129 in the source.

**Comment by m1pro** [comment]
OS: macOS 12.4
Word size of FreeCAD: 64-bit
Version: 2022.430.26244 +4758 (Git)
Build type: Release
Branch: LinkDaily
Hash: b024b876480a533018fdc702145e9e38f8c54ba6
Python version: 3.9.10
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: English/Israel (en_IL)


mmm, ok I will check with other OS (ubuntu)/version
on the above at least I don't see it working (including double click on the Animator icon to stop)

**Comment by m1pro** [comment]
OS: macOS 12.4
Word size of FreeCAD: 64-bit
Version: 2022.430.26244 +4758 (Git)
Build type: Release
Branch: LinkDaily
Hash: b024b876480a533018fdc702145e9e38f8c54ba6
Python version: 3.9.10
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0

mmm, ok I will check with other OS (ubuntu)/version
on the above at least I don't see it working (including double click on the Animator icon to stop)

**Comment by mwganson** [comment]
Works okay here.  I just tested.  Maybe there is some issue with Link version.  I'm running 0.20 on windows.

[code]
OS: Windows 10 (10.0)
Word size of FreeCAD: 64-bit
Version: 0.20.28751 (Git)
Build type: Release
Python 3.8.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.56 (Disabled)
  * Assembly4 0.11.12
  * BOLTSFC
  * CurvedShapes 1.0.3
  * Curves 0.3.0
  * DynamicData 2.46.0
  * fasteners
  * FCGear
  * FreeCAD_mcm_addon
  * gears
  * hfcInventorMentorA
  * InvGears
  * lattice2
  * Manipulator
  * MeshRemodel 1.8919.0
  * POV-Ray-Rendering
  * sheetmetal 0.2.49
  * ThreadProfile 1.81.0
[/code]
